AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/EndOfLine:
  EnforcedStyle: lf

# Disable documentation requirements for specs
Style/Documentation:
  Enabled: true
  Exclude:
    - "spec/**/*"

# Allow longer blocks in specs
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "spec/**/*"
    - "*.gemspec"
