version: 2.1
jobs:
  build:
    docker:
      - image: ruby:3.3.5
    steps:
      - checkout
      - run:
          name: Set execute permissions
          command: chmod +x bin/console
      - run:
          name: Run the default task
          command: |
            gem install bundler -v 2.6.3
            bundle install
            bundle exec rake
